# Generated by Django 3.1 on 2020-08-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.TextField(unique=True)),
                ('full_url', models.TextField()),
                ('media', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweet_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='urls',
            field=models.ManyToManyField(to='tweets.Url'),
        ),
    ]
